### ISSUE TITLE
Boiler plate contracts

### ISSUE THREAD

**Issue by mgifford** [DISIC/foss-contrib-policy-template#10]
So much of the problem with open source & government lies with procurement & contracts.

It would be terrific to include some default language for contracts that governments can use to ensure that open source is favoured rather either the contractor or institution being given intellectual property rights.  

> All software developed through this contract will be the copyright of THE DEVELOPER and licensed under the INSERT PREFERRED OPEN-SOURCE LICENSE to ensure that the software may be freely used, modified and distributed. Any documentation written as part of this contract will be similarly licensed under the Creative Commons Share Alike License.

It should be set out clearly in the contracting phase.

**Comment by gregkh** [comment]
That would be wonderful, but I think it's outside the scope of this document.  This document is to allow contributions to existing projects or opening of new ones, not to deal with procurement.
