### ISSUE TITLE
Centralise discussions on GitHub

### ISSUE THREAD

**Issue by MattiSG** [DISIC/foss-contrib-policy-template#11]
The [referenced](https://forum.etalab.gouv.fr/c/gouvernement-ouvert/FOSS-contrib-policy) “Discussions around this open-source policy” (the @Etalab forum) is down.

However, beyond fixing the SSL setup which is not the responsibility of this repo, it would make sense to ensure all information is centralised in one place, and not spread across several points. Importing the conclusions of that discussion in the README and the open questions as issues would make it easier to contribute.

**Comment by bzg** [comment]
Closing as obsolete.
