### ISSUE TITLE
clarify language/message re: inbound/outbound licensing

### ISSUE THREAD

**Issue by jlovejoy** [DISIC/foss-contrib-policy-template#6]
Hi, I wanted to make sure I understand the aims in the section regarding licenses before suggesting changes:
- Should the terms "inbound" and "outbound" license be used as this is used generally and makes it easier to distinguish or identify whether you are talking about the license for contributions or the license for using the code (or when they are the same)? This seems to be what is used commonly elsewhere.
- in Contributing to Existing Open Source Projects --> Evaluate the Project License section, it states: "ENTITY_NAME’s civil servants and subcontractors can only contribute to projects that have a clearly defined license that is approved by ENTITY_NAME and available at ACCEPTED_LICENSES_URL." - should this be clarified to: "... projects that have a clearly defined inbound and outbound license ... " Reason being that many projects are not good at identifying the license, or making it clear under what license contributions are accepted (we all need to do a better job of this...)
- in Releasing and Managing Open Source Projects --> Licenses:
-- it says, "Whenever possible, the new project shall use a target license ensuring compatibility with corresponding FOSS projects ecosystem." - maybe change "target license" to "outbound license"
-- where it says, "A CLA should not be required for the project. Instead, a process like the Developer’s Certificate of Origin (DCO), can be used to verify that developers agree with the project’s license, if so desired." - I think the goal here is to default to inbound = outbound (with use of DCO) - is that correct?  If so, I'd recommend changes to state this explicitly (but wanted to check as to the goal first).
Thanks and sorry this is a long comment... 
Jilayne

**Comment by camillem** [comment]
Hi, 
About your last point : 
> I think the goal here is to default to inbound = outbound (with use of DCO) - is that correct? 

Yes it is, indeed.

Camille

**Comment by jlovejoy** [comment]
Thanks Camille, that's what I thought.  I've added a bit of language to make this clear.

**Comment by gregkh** [comment]
This should all be resolved with pull request 6 and 7 now, correct?

**Comment by gregkh** [comment]
Closing as this should be resolved.
